In [2]:
!curl -LsSf https://astral.sh/uv/install.sh | sh

downloading uv 0.11.1 x86_64-unknown-linux-gnu
installing to /home/codespace/.local/bin
  uv
  uvx
everything's installed!

In [3]:
!uv self update

info: Checking for updates...
success: You're already on version v0.11.1 of uv (the latest version).

#CREATING VIRTUAL ENVIRONMENT
    1  uv venv mlgabriel
    2  source mlgabriel/bin/activate
    3  uv pip install ipykernel
    4  python -m ipykernel install --user --name=mlgabriel

In [3]:
!uv pip install numpy 
!uv pip install pandas

Using Python 3.12.1 environment at: mlgabriel
Checked 1 package in 1ms

Using Python 3.12.1 environment at: mlgabriel
Checked 1 package in 2ms

In [4]:
import numpy as np
import pandas as pd

In [5]:
s = pd.Series([1,2,5,np.nan,6,8])

s

0    1.0
1    2.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [6]:
date = pd.date_range("20260102", periods=6)

date

DatetimeIndex(['2026-01-02', '2026-01-03', '2026-01-04', '2026-01-05',
               '2026-01-06', '2026-01-07'],
              dtype='datetime64[us]', freq='D')

In [9]:
df = pd.DataFrame(np.random.randn(6,4), index=date, columns=list("ABCD"))

df

                   A         B         C         D
2026-01-02 -1.092591 -0.035668  0.540206  0.620763
2026-01-03  0.420399 -2.127554 -0.406994 -0.136503
2026-01-04 -0.866028 -1.491493  1.586101  0.311146
2026-01-05  0.509523  1.188788  1.409322  0.382337
2026-01-06  1.417075 -0.891347  0.434260 -0.869621
2026-01-07  0.327265  0.541754 -0.070801 -0.462723

In [12]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp(20260326),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3]*4,dtype="int32"),
        "E": pd.Categorical(["test", "train","test", "train"]),
        "F": "foo"
    }
)

df2

     A                             B    C  D      E    F
0  1.0 1970-01-01 00:00:00.020260326  1.0  3   test  foo
1  1.0 1970-01-01 00:00:00.020260326  1.0  3  train  foo
2  1.0 1970-01-01 00:00:00.020260326  1.0  3   test  foo
3  1.0 1970-01-01 00:00:00.020260326  1.0  3  train  foo